import json
import aiorequests
import io
import os
import base64
from PIL import Image
from nonebot import on_command, on_message, on_notice, on_regex, get_driver
from nonebot.typing import T_State
from nonebot.adapters import Event, Bot
from nonebot.adapters.cqhttp import Message
from aiocqhttp import MessageSegment
import aiohttp, os
from src.libraries.tool import hash
from src.libraries.maimaidx_music import *
from src.libraries.image import *
from src.libraries.maimai_best_40 import generate
from src.zyj import *
import re
import time, datetime
from PIL import Image, ImageDraw, ImageFont
from io import BytesIO
import requests, json, time, math

url = "https://view.inews.qq.com/g2/getOnsInfo?name=disease_h5"  # 腾讯api

yiqing = on_regex(r".+疫情")


@yiqing.handle()
async def _(bot: Bot, event: Event, state: T_State):
    regex = "(.+)疫情"
    area = re.match(regex, str(event.get_message())).groups()[0].strip().lower()
    print(area)
    # 应该不会有人闲到写全称吧
    if area == "内蒙古自治区":
        area = "内蒙古"
    elif area == "宁夏回族自治区":
        area = "宁夏"
    elif area == "新疆维吾尔自治区":
        area = "新疆"
    elif area == "西藏自治区":
        area = "西藏"
    elif area == "广西壮族自治区":
        area = "广西"
    type_ = ""  # 标记是省还是市
    result = {}
    msg = ""
    async with aiohttp.request("POST", url) as resp:
        raw_data = await resp.json()
    if raw_data['ret'] != 0:
        print('ret不为0，疑似有问题')
    data = json.loads(raw_data['data'])
    tree = data['areaTree']
    all_province = tree[0]['children']

    # 先最特殊情况
    if area in ("中国","全国","国内"):
        data.pop("areaTree")
        msg += f"中国（含港澳台）疫情：\n"
        msg += f"现存确诊{data['chinaTotal']['nowConfirm']}(+{data['chinaAdd']['confirm']})\n"
        try:
            msg += f"现存疑似{data['chinaTotal']['suspect']}(+{data['chinaAdd']['suspect']})\n"
        except:
            msg += "无法获取疑似病例数据\n"
        msg += f"累计确诊{data['chinaTotal']['confirm']}\n"
        msg += f"累计治愈{data['chinaTotal']['heal']}\n"
        msg += f"累计死亡{data['chinaTotal']['dead']}\n"
        return msg
    elif area == "吉林市":
        for province in all_province:
            if province['name'] == "吉林":
                for city in province['children']:
                    if city['name'] == "吉林":
                        result = city
                        type_ = "(市)"
    else:
        # 移除“市”
        if area[-1] == "市":
            area = area[0:-1]
        # 先找省
        if area[-1] == "省":
            # 针对指定为省份的查询
            for province in all_province:
                if province['name'] == area[0:-1]:
                    province.pop('children')
                    result = province
                    type_ = "(省)"
        else:
            # 不会优化，两个for嗯找，能跑就行
            for province in all_province:
                if province['name'] == area and "省" not in area:
                    # 没有写“省”字，但要找的确实是一个省
                    province.pop('children')
                    result = province
                    type_ = "(省)"
                    break
                for city in province['children']:
                    if city['name'] == area:
                        result = city
                        type_ = "(市)"
    if area in ['北京', '天津', '重庆', '上海']:
        type_ = "(直辖市)"
    elif area in ['香港', '澳门']:
        type_ = "(特别行政区)"
    msg += f"{result['name']}{type_}疫情：\n"
    msg += f"现存确诊：{result['total']['nowConfirm']}" + (
        f"(+{result['today']['confirm']})" if result['today']['confirm'] > 0 else "")
    msg += "\n"
    try:
        msg += f"现存疑似：{result['total']['suspect']}\n"
    except:
        msg += f"无法获取疑似病例数据\n"
    msg += f"累计确诊：{result['total']['confirm']}\n"
    try:
        msg += f"累计死亡：{result['total']['dead']} ({result['total']['deadRate']}%)\n"
    except:
        msg += f"累计死亡：{result['total']['dead']} ({(result['total']['dead'] / result['total']['confirm'] * 100):.2f}%)\n"
    try:
        msg += f"累计治愈：{result['total']['heal']} ({result['total']['healRate']}%)\n"
    except:
        msg += f"累计治愈：{result['total']['heal']} ({(result['total']['heal'] / result['total']['confirm'] * 100):.2f}%)\n"
    try:
        msg += f"风险等级：{result['total']['grade']}\n" if type_ == "(市)" else ""
    except:
        pass
    msg += f"最后更新时间：\n{data['lastUpdateTime']}\n"
    msg += f"Generated by Eurobot & plugins\n"

    try:  # 不知道稳不稳，先用try包一下
        url_risk_area = "https://wechat.wecity.qq.com/api/PneumoniaTravelNoAuth/queryAllRiskLevel"
        payload_json = {"args": {"req": {}}, "service": "PneumoniaTravelNoAuth", "func": "queryAllRiskLevel",
                        "context": {"userId": "a"}}
        risk_area_data = await aiorequests.post(url=url_risk_area, json=payload_json)
        risk_area_data = await risk_area_data.json()
        risk_area_data = risk_area_data['args']['rsp']
        mediumRiskAreaList = risk_area_data['mediumRiskAreaList']
        highRiskAreaList = risk_area_data['highRiskAreaList']
        
        
        # （吉林市上面没移除“市”）
        if area[-1] == "市":
            area = area[0:-1]
        
        msg += '\n中风险地区：\n'
        mid_risk_msg = ''
        for i in mediumRiskAreaList:
            for j in i['list']:
                if j['cityName'] in [area, area + "市"]:
                    mid_risk_msg += f"  {j['areaName']} {j['communityName']}\n"
        if len(mid_risk_msg) > 0:
            mid_risk_msg = mid_risk_msg.replace('、', '\n  ')
            msg += mid_risk_msg + '\n'
        else:
            msg += '  N/A\n'

        msg += '高风险地区：\n'
        high_risk_msg = ''
        for i in highRiskAreaList:
            for j in i['list']:
                if j['cityName'] in [area, area + "市"]:
                    high_risk_msg += f"  {j['areaName']} {j['communityName']}\n"
        if len(high_risk_msg) > 0:
            high_risk_msg = high_risk_msg.replace('、', '\n  ')
            msg += high_risk_msg + '\n'
        else:
            msg += '  N/A\n'
    except:
        pass
    fontpath = font_path = os.path.join(os.path.dirname(__file__), 'simhei.ttf')
    font1 = ImageFont.truetype(fontpath, 16)
    width, height = font1.getsize_multiline(msg.strip())
    img = Image.new("RGB", (width + 20, height + 20), (255, 255, 255))
    draw = ImageDraw.Draw(img)
    draw.text((10, 10), msg, fill=(0, 0, 0), font=font1)
    b_io = io.BytesIO()
    img.save(b_io, format="JPEG")
    base64_str = 'base64://' + base64.b64encode(b_io.getvalue()).decode()
    await yiqing.send(msg)